### ISSUE TITLE
Error: render error in "argus/charts/collectorset-controller/templates/secret.yaml

### ISSUE THREAD

**Issue by assafShapira** [logicmonitor/k8s-argus#75]
-   **Argus Version:**
lates
-   **Kubernetes Version:**
1.10

when trying to install the chart, according to the documentation, I'm getting the following error

Error: render error in "argus/charts/collectorset-controller/templates/secret.yaml": template: argus/charts/collectorset-controller/templates/secret.yaml:7:15: executing "argus/charts/collectorset-controller/templates/secret.yaml" at <required "A valid .V...>: error calling required: A valid .Values.global.accessID entry is required!

the command I've tried:
helm upgrade --install --set accessID='$ACCESS_ID' --set accessKey='$ACCESS_KEY' argus logicmonitor/argus

I may be missing something in the documentation, but I think there is something missing there, or and issue in the chart

**Comment by woz5999** [comment]
The key in the --set should be namespaced. For example: --set global.accessID

Let me know if this resolves your issue.

**Comment by assafShapira** [comment]
that works
thank
