### ISSUE TITLE
cant apply 

### ISSUE THREAD

**Issue by sagivle** [logicmonitor/k8s-argus#83]
-   **Argus Version:** 0.2.0-alpha.0
-   **Kubernetes Version:** 1.10.5-gke.4
-   **Docker Version:**

kubectl apply -f collectorset.yaml
error: error converting YAML to JSON: yaml: line 1: mapping values are not allowed in this context

collectorset.yaml:
apiVersion: logicmonitor.com/v1alpha1
  kind: CollectorSet
  metadata:
    name: k8s-test-europe-west1
    namespace: logicmonitor
  spec:
    policy:
      distributionStrategy: RoundRobin
      orchestrator: Kubernetes
    replicas: 2
    size: medium

**Comment by skt44** [comment]
@sagivle can you confirm that the indentation is correct? It should look like this:
`apiVersion: logicmonitor.com/v1alpha1
kind: CollectorSet
metadata:
  name: k8s-test-europe-west1
  namespace: logicmonitor
spec:
  policy:
    distributionStrategy: RoundRobin
    orchestrator: Kubernetes
  replicas: 2
  size: medium`

**Comment by sagivle** [comment]
this is what i am using :
#!/usr/bin/env bash

NAMESPACE=default
ACCESS_ID="bbb"
ACCESS_KEY="ccc"
ACCOUNT=jfrog
CLUSTER_NAME=k8s-test-europe-west1
COLLECTOR_DESCRIPTION=k8s-testing
COLLECTORIMAGETAG=lm_collector
COLLECTORSIZE=medium

kubectl create serviceaccount tiller --namespace kube-system
kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
helm init --service-account=tiller

helm repo add logicmonitor https://logicmonitor.github.com/k8s-helm-charts

helm upgrade --debug --install --version 0.2.0 \
    --set collectorset-controller.imageTag=0.1.0-alpha.1 \
    --set global.accessID="$ACCESS_ID" \
    --set global.accessKey="$ACCESS_KEY" \
    --set global.account="$ACCOUNT" \
    --set enableRBAC="false"  \
    --set collectorset-controller.enableRBAC="false" \
    --set clusterName="$CLUSTER_NAME" \
    --set imageTag=0.2.0-alpha.1 \
    argus logicmonitor/argus

collectorset.yaml:

apiVersion: logicmonitor.com/v1alpha1
kind: CollectorSet
metadata:
  name: k8s-test-europe-west1
  namespace: default
spec:
  policy:
    distributionStrategy: RoundRobin
    orchestrator: Kubernetes
  replicas: 2
  size: medium

kubectl apply -f collectorset.yaml

getting:

time="2018-08-13T09:56:49Z" level=fatal msg="Failed waiting for gRPC to ready, state is \"CONNECTING\""

**Comment by skt44** [comment]
@sagivle you may need the enableRBAC lines in the install to be set to true. Try the instructions here: https://logicmonitor.github.io/k8s-argus/getting-started/

**Comment by sagivle** [comment]
will it work on an RBAC disabled (k8s)?
trying to set it to true will give error:
Error: UPGRADE FAILED: failed to create resource: clusterroles.rbac.authorization.k8s.io "collectorset-controller" is forbidden: attempt to grant extra privileges: [PolicyRule{APIGroups:[""], Resources:["pods"], Verbs:["*"]} PolicyRule{APIGroups:["apps"], Resources:["statefulsets"], Verbs:["*"]} PolicyRule{APIGroups:["*"], Resources:["collectorsets"], Verbs:["*"]} PolicyRule{APIGroups:["apiextensions.k8s.io"], Resources:["customresourcedefinitions"], Verbs:["*"]}] user=&{system:serviceaccount:kube-system:default 7a5d64564533d5-965464565d-116546e8-9b98-54646465 [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} ownerrules=[PolicyRule{APIGroups:["authorization.k8s.io"], Resources:["selfsubjectaccessreviews" "selfsubjectrulesreviews"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/openapi" "/openapi/*" "/swagger-2.0.0.pb-v1" "/swagger.json" "/swaggerapi" "/swaggerapi/*" "/version" "/version/"], Verbs:["get"]}] ruleResolutionErrors=[]
collectorset "k8s-test" configured

**Comment by skt44** [comment]
@sagivle yes - setting enableRBAC to false will resolve that error.
