### ISSUE TITLE
No Helm

### ISSUE THREAD

**Issue by MarkDeckert** [logicmonitor/k8s-argus#89]
Please include a deployment method that doesn't require Helm.  We're trying to avoid Helm as much as possible (for many reasons I won't go into here).  It's very simple to edit normal k8s manifests so I don't see much benefit to abstracting it through helm for this case.

**Comment by woz5999** [comment]
Hi Mark,
Helm is the only supported deployment method for Argus at this time. 

The chart resource templates can be found here: https://github.com/logicmonitor/k8s-helm-charts/tree/master/argus/templates

The resources templates in the chart aren't particularly complex, so you should be able to manually create manifests the manifests for your needs and particular configuration options.
